name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # - cudatoolkit=11.8
  - plyfile
  # - python=3.10.12
  - pip
  # - pytorch 
  # - torchaudio
  # - torchvision
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
